config/routes.rb
=begin
Copyright 2017 Alessandro Profiti, Gabriele Restuccia, Lorenzo Ricelli.

This file is part of PagoChiNonPaga.

PagoChiNonPaga is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PagoChiNonPaga is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
=end

Rails.application.routes.draw do
  # Pagine Statiche
  #get 'static_pages/home_page'
  get '/registrati', to:'static_pages#registrati'
  get '/infoCarrello', to:'static_pages#carrello_mancante'
  #get '/login', to: 'devise/sessions#new', as: :login
  # Rotte per RailsAdmin
  mount RailsAdmin::Engine => '/cp', as: 'rails_admin'

  resources :poli, except: [:new,:edit], param: :nome, :nome => /[^\/]+/
  devise_for :utenti, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout"}
  devise_for :admins
  resources :citta, except: [:new,:edit] , param: :nome , :nome => /[^\/]+/
  resources :ordini, except: :new, path: '/mieiOrdini' do
    member do
      post :prepara_ordini
      post :paypal_url
      get :checkout
    end
  end
  get "imprese/autocomplete" => "imprese#autocomplete"

  #PATH del tipo /imprese/:nome/prodotti/:nome
  resources :imprese, param: :nome , :nome => /[^\/]+/ do
    resources :prodotti,except: [:show], param: :nome, :nome => /[^\/]+/ do
      post :elimina_prodotto
    end
  end

  #PATH del tipo /categorie/:nome/sottocategorie/:nome
  resources :categorie, except: [:show,:new,:edit], param: :nome, :nome => /[^\/]+/ do  #Il parametro ora è il nome e non l'id
    resources :sottocategorie, except: [:new,:edit], param: :nome , :nome => /[^\/]+/   #Il parametro ora è il nome e non l'id
  end

  resources :titolari, except: [:index]
  resources :clienti, except: [:index]


  resources :carrello, except: [:index, :new,:edit] do
    member do
      post :remove_item
      post :add_cart
      post :aggiungi_quantita
      post :sottrai_quantita
    end
  end

  root 'static_pages#home_page'
  get '*unmatched_route', :to => 'static_pages#render_404'

#*********************ROTTE CANCELLATE************************
  #resources :admins perchè si accede da rails_admin
  #resources :utenti
#*************************************************************

end

app/models/carrello.rb
=begin
Copyright 2017 Alessandro Profiti, Gabriele Restuccia, Lorenzo Ricelli.

This file is part of PagoChiNonPaga.

PagoChiNonPaga is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PagoChiNonPaga is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
=end

class Carrello < ActiveRecord::Base
  # Gemma Carrello
  acts_as_shopping_cart_using :carrello_prodotti
  # Associo ogni carrello ad un cliente
  belongs_to :cliente

  validates :cliente_id, presence: true

  # Necessario per mostrare il nome dell'Entita in RailsAdmin
  def name
    cliente = self.cliente
    # Controllo che ci sia il record prima di visualizzare nel pannello
    if cliente != nil
      cliente.getNome
    end
  end

  # Ritorna lista imprese interessate nel carrello, richiamato in controller ordini
  def impreseCarrello
    imprese = []
    self.impresaElemento.each do |tupla|
      if !(imprese.include? tupla.at(0))
        imprese << tupla.at(0)
      end
    end
    imprese
  end

  # Ritorna lista prodotti carrello con [id_impresa, elemento], richiamato in impreseCarrello e in controller ordini
  def impresaElemento
    ids=[]
    self.cart_items.each do |elemento|
      prodotto = Prodotto.find(elemento.item_id)
      ids << [prodotto.impresa_id,elemento]
    end
    ids
  end

end

app/controllers/carrello_controller.rb
=begin
Copyright 2017 Alessandro Profiti, Gabriele Restuccia, Lorenzo Ricelli.

This file is part of PagoChiNonPaga.

PagoChiNonPaga is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PagoChiNonPaga is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
=end

class CarrelloController < ApplicationController
  before_action :set_carrello, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_utente!
  before_filter :is_my_carrello?


  # GET /carrello/:id
  # GET /carrello/:id.json
  def show
  end

  # POST /carrello/:id/remove_item
  def remove_item #rimuove item da carrello
    carrello = current_utente.getCarrello
    carrello.cart_items.delete(params[:item].to_i)  #item è un parametro che arriva dalla post
    redirect_to carrello_path(id: carrello.id)
  end

  # POST /carrello/:id/add_cart
  # Aggiunge al carrello il prodotto presente nella pagina in cui viene richamato
  def add_cart
    if current_utente.hasCarrello?
      carrello= current_utente.getCarrello
    else
      carrello= Carrello.create(cliente_id: current_utente.actable_id)
    end
    prodotto= Prodotto.find(params[:prodotto_id])
    qta_post = params[:prodotto][:qta].to_i
    if prodotto.checkDisponibilita(qta_post,carrello)
      carrello.add(prodotto,prodotto.prezzo,qta_post)
      flash[:success] = "Prodotto aggiunto al carrello."
      redirect_back
    else
      flash[:notice] = "Quantita selezionata non disponibile."
      redirect_to(:back)
    end
  end

  def aggiungi_quantita
    prodotto= CarrelloProdotto.find(params[:item])
    prodotto.aggiungiQuantita
    redirect_to carrello_path(id: params[:carrello_id])
  end

  def sottrai_quantita
    prodotto= CarrelloProdotto.find(params[:item])
    prodotto.scalaQuantita
    if !prodotto.changed?
      flash[:error] = "Impossibile scalare la quantità"
    end
    redirect_to carrello_path(id: params[:carrello_id])
  end
  # POST /carrello
  # POST /carrello.json
  def create
    @carrello = Carrello.new(carrello_params)

    respond_to do |format|
      if @carrello.save
        format.html { redirect_to @carrello, notice: 'Carrello was successfully created.' }
        format.json { render :show, status: :created, location: @carrello }
      else
        format.html { render :new }
        format.json { render json: @carrello.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /carrello/:id
  # DELETE /carrello/:id.json
  def destroy
    @carrello.destroy
    respond_to do |format|
      format.html { redirect_to carrello_index_url, notice: 'Carrello was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def is_my_carrello?
      if @carrello != nil
        if !(current_utente.isCliente? && @carrello.cliente_id == current_utente.actable_id)
          redirect_back
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_carrello
      @carrello = Carrello.find(params[:id])
    end

    def carrello_params
      params.fetch(:carrello, {})
    end
end

app/views/carrello/show.html.erb
<%- model_class = Carrello -%>
<div class="container">
  <div class="page-header">
    <h1>Il mio <%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th width = "20%"><%= model_class.human_attribute_name(:image) %></th>
            <th><%= model_class.human_attribute_name(:nome) %></th>
            <th><%= model_class.human_attribute_name(:impresa) %></th>
            <th><%= model_class.human_attribute_name(:prezzo) %></th>
            <th><%= model_class.human_attribute_name(:quantita) %></th>
            <th><%= model_class.human_attribute_name(:azioni) %></th>
          </tr>
        </thead>
        <tbody>
            <!-- Prodotti nel carrello -->
            <% @carrello.cart_items.each do |item| %>
            <% prodotto = Prodotto.find(item.item_id) %>
              <tr>
                <td><%= image_tag(prodotto.image, :class => "img-responsive") %></td>
                <td><%= link_to prodotto.nome, impresa_prodotti_path(id: prodotto.id, impresa_nome: prodotto.impresa.getNome) %></td>
                <td><%= prodotto.impresa.getNome %></td>
                <td><%= item.price %></td>
                <td>
                  <%= link_to sottrai_quantita_carrello_path(item: item.id,carrello_id: @carrello.id), :class => "btn btn-default btn-xs", method: :post do %>
                    <span class="fa fa-minus"></span>
                  <% end %>
                  <%= item.quantity %>
                  <%= link_to aggiungi_quantita_carrello_path(item: item.id,carrello_id: @carrello.id), :class => "btn btn-default btn-xs", method: :post do %>
                    <span class="fa fa-plus"></span>
                  <% end %>
                </td>
                <td><%= link_to "Rimuovi", remove_item_carrello_path(id: params[:id],item: item),
                        :class => 'btn btn-danger btn-xs', method: :post %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="pull-right">
          <dl class="dl-horizontal">
            <dt><strong><%= model_class.human_attribute_name(:totale) %>:</strong></dt>
            <dd><%= @carrello.subtotal%></dd>
          </dl>
        </div>
        <div class="pull-right">
          <p>La <%= model_class.human_attribute_name(:spedizione) %> verra' aggiunta dal venditore dopo aver confermato l'ordine</p>
        </div>
    </div>
    <div class="panel-footer">
      <% if @carrello.has_items? %>
        <%= button_to "Procedi all'acquisto", prepara_ordini_ordine_path(id: current_utente.actable_id), :class => "btn btn-primary pull-right", method: :post%>
      <% end %>




      <!-- TODO eliminare?? -->

      <% if current_utente.actable_type == "Cliente" %>
        <%= link_to t('.vaiAlProfilo', :default => t("helpers.links.vaiAlProfilo")),
                    cliente_path(id: current_utente.actable_id), :class => 'btn btn-default', method: :get%>
      <% else %>
        <%= link_to t('.profilo', :default => t("helpers.links.profilo")),
                    titolare_path(id: current_utente.actable_id), :class => 'btn btn-default', method: :get%>
      <% end %>
    </div>
  </div>
</div>