config/routes.rb
=begin
Copyright 2017 Alessandro Profiti, Gabriele Restuccia, Lorenzo Ricelli.

This file is part of PagoChiNonPaga.

PagoChiNonPaga is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PagoChiNonPaga is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
=end

Rails.application.routes.draw do
  # Pagine Statiche
  #get 'static_pages/home_page'
  get '/registrati', to:'static_pages#registrati'
  get '/infoCarrello', to:'static_pages#carrello_mancante'
  #get '/login', to: 'devise/sessions#new', as: :login
  # Rotte per RailsAdmin
  mount RailsAdmin::Engine => '/cp', as: 'rails_admin'

  resources :poli, except: [:new,:edit], param: :nome, :nome => /[^\/]+/
  devise_for :utenti, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout"}
  devise_for :admins
  resources :citta, except: [:new,:edit] , param: :nome , :nome => /[^\/]+/
  resources :ordini, except: :new, path: '/mieiOrdini' do
    member do
      post :prepara_ordini
      post :paypal_url
      get :checkout
    end
  end
  get "imprese/autocomplete" => "imprese#autocomplete"

  #PATH del tipo /imprese/:nome/prodotti/:nome
  resources :imprese, param: :nome , :nome => /[^\/]+/ do
    resources :prodotti,except: [:show], param: :nome, :nome => /[^\/]+/ do
      post :elimina_prodotto
    end
  end

  #PATH del tipo /categorie/:nome/sottocategorie/:nome
  resources :categorie, except: [:show,:new,:edit], param: :nome, :nome => /[^\/]+/ do  #Il parametro ora è il nome e non l'id
    resources :sottocategorie, except: [:new,:edit], param: :nome , :nome => /[^\/]+/   #Il parametro ora è il nome e non l'id
  end

  resources :titolari, except: [:index]
  resources :clienti, except: [:index]


  resources :carrello, except: [:index, :new,:edit] do
    member do
      post :remove_item
      post :add_cart
      post :aggiungi_quantita
      post :sottrai_quantita
    end
  end

  root 'static_pages#home_page'
  get '*unmatched_route', :to => 'static_pages#render_404'

#*********************ROTTE CANCELLATE************************
  #resources :admins perchè si accede da rails_admin
  #resources :utenti
#*************************************************************

end

app/views/shared/_barra_navigazione.html.erb
<!-- Barra Navigazione -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- Logo -->
      <%= link_to root_path, method: :get do %>
        <%= image_tag "template/logo/ap_grey.png", :id => "logo", :class => "img-responsive" %>
      <% end %>
      <!-- Mostra menu su schermi piccoli-->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- Contenuto Barra -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path ,method: :get%></li>
        <li><%= link_to "Imprese", imprese_path, method: :get %></li>
        <li><%= link_to "Categorie", categorie_path, method: :get %></li>
        <% if utente_signed_in? %>
          <% if current_utente.isCliente?%>
            <% if  current_utente.hasCarrello? %>
              <li><%= link_to "Carrello",  carrello_path(current_utente.getCarrello) ,method: :get%></li>
            <% else %>
              <li><%= link_to "Carrello",  infoCarrello_path,method: :get %></li>
            <% end %>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_utente.getNome() %>
              <span class="fa fa-user"></span>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <% if current_utente.isCliente? %>
                  <li><%= link_to "Profilo", cliente_path(id: current_utente.actable_id) ,method: :get%></li>
              <% elsif current_utente.isTitolare? %>
                  <li><%= link_to "Profilo", titolare_path(id: current_utente.actable_id) ,method: :get%></li>
              <% end %>
              <li><%= link_to "Ordini", ordini_path,method: :get %></li>
              <li><%= link_to "Log out", destroy_utente_session_path, :method => :delete %></li>
            </li>
            <% else %>
              <li><%= link_to "Accedi", new_utente_session_path ,method: :get%></li>
              <li><%= link_to "Registra",registrati_path ,method: :get%></li>
            <% end %>
            </ul>
      </ul>
      <!-- Barra di Ricerca -->
      <% #  L'if controlla che la pagina corrente non sia index imprese, index categorie o lo show di sottocategorie.
         #  Controllo controller_nameperchè controllare lo show richiederebbe parametro e non sarebbe generico. Se non è una di quelle viene fatto render barra ricerca in alto
      %>
      <% if !current_page?(imprese_path) && !current_page?(categorie_path) && controller.controller_name!='sottocategorie' && controller.action_name!= 'render_404'%>
          <%= render "shared/barra_ricerca" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_barra_ricerca.html.erb
<%= form_tag(impresa_path(:impresa , :id), method: "get", class: "navbar-form navbar-center") do %>
  <div class="form-group" style="width: 30%;">
  <%= text_field_tag :impresa ,"", class: "form-control typeahead", style: "width:100%;" %>
     <%= hidden_field_tag "id", "", :id => "id_imp" %>
  </div>
  <%= button_tag(type: 'submit',id: "typesearch", class: "btn btn-default", style: "background-color:#F5A623;") do %>
    <span class="glyphicon glyphicon-search">
  <% end %>
<% end %>