config/routes.rb
=begin
Copyright 2017 Alessandro Profiti, Gabriele Restuccia, Lorenzo Ricelli.

This file is part of PagoChiNonPaga.

PagoChiNonPaga is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PagoChiNonPaga is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
=end

Rails.application.routes.draw do
  # Pagine Statiche
  #get 'static_pages/home_page'
  get '/registrati', to:'static_pages#registrati'
  get '/infoCarrello', to:'static_pages#carrello_mancante'
  #get '/login', to: 'devise/sessions#new', as: :login
  # Rotte per RailsAdmin
  mount RailsAdmin::Engine => '/cp', as: 'rails_admin'

  resources :poli, except: [:new,:edit], param: :nome, :nome => /[^\/]+/
  devise_for :utenti, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout"}
  devise_for :admins
  resources :citta, except: [:new,:edit] , param: :nome , :nome => /[^\/]+/
  resources :ordini, except: :new, path: '/mieiOrdini' do
    member do
      post :prepara_ordini
      post :paypal_url
      get :checkout
    end
  end
  get "imprese/autocomplete" => "imprese#autocomplete"

  #PATH del tipo /imprese/:nome/prodotti/:nome
  resources :imprese, param: :nome , :nome => /[^\/]+/ do
    resources :prodotti,except: [:show], param: :nome, :nome => /[^\/]+/ do
      post :elimina_prodotto
    end
  end

  #PATH del tipo /categorie/:nome/sottocategorie/:nome
  resources :categorie, except: [:show,:new,:edit], param: :nome, :nome => /[^\/]+/ do  #Il parametro ora è il nome e non l'id
    resources :sottocategorie, except: [:new,:edit], param: :nome , :nome => /[^\/]+/   #Il parametro ora è il nome e non l'id
  end

  resources :titolari, except: [:index]
  resources :clienti, except: [:index]


  resources :carrello, except: [:index, :new,:edit] do
    member do
      post :remove_item
      post :add_cart
      post :aggiungi_quantita
      post :sottrai_quantita
    end
  end

  root 'static_pages#home_page'
  get '*unmatched_route', :to => 'static_pages#render_404'

#*********************ROTTE CANCELLATE************************
  #resources :admins perchè si accede da rails_admin
  #resources :utenti
#*************************************************************

end

app/controllers/prodotti_controller.rb
=begin
Copyright 2017 Alessandro Profiti, Gabriele Restuccia, Lorenzo Ricelli.

This file is part of PagoChiNonPaga.

PagoChiNonPaga is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PagoChiNonPaga is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
=end

class ProdottiController < ApplicationController
  before_action :set_prodotto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_utente!, only: [:new, :edit]
  before_filter :id_index_match, only: :index
  before_filter :prodotto_impresa_match , only: [:show, :edit]
  before_filter :impresa_abilitata , only: [:show, :edit,:destroy,:update]
  before_filter :titolare_paypal?
  # GET /imprese/:impresa_nome/prodotti/:nome?id=id_impresa
  # GET /imprese/:impresa_nome/prodotti/:nome.json?id=id_impresa
  def index       #rotta rimossa
    impresa= Impresa.find(params[:id].to_i)     #prima di index controllo che l'id inserito corrisponda a una impresa verificata e NON congelata
    if !(impresa.verificato && !(impresa.congelato))
      redirect_back
    else
      @prodotti = Prodotto.where(impresa_id: params[:id])
    end
  end

  # GET /imprese/:impresa_nome/prodotti/:nome?id_p=id_prodotto
  # GET /imprese/:impresa_nome/prodotti/:nome.json?id_p=id_prodotto
  def show
  end

  # GET /imprese/:impresa_nome/prodotti/new?id=id_impresa
  def new
   imp_list = Impresa.where(titolare_id: current_utente.actable_id).select("id") #imp_list contiene lista imprese del titolare loggato
   if !(current_utente.actable_type == "Titolare" && (imp_list.ids.include? params[:id].to_i ))  #se l'impresa attuale non è sua ho redirect
     redirect_back
   end
    @prodotto = Prodotto.new
  end

  # GET /imprese/:impresa_nome/prodotti/:nome/edit?id_p=id_prodotto
  def edit
   imp_list = Impresa.where(titolare_id: current_utente.actable_id).select("id")
   if !(current_utente.actable_type == "Titolare" && (imp_list.ids.include? @prodotto.impresa_id.to_i ))
     redirect_back
   end
  end

  # POST /imprese/:impresa_nome/prodotti?id=id_impresa
  # POST /imprese/:impresa_nome/prodotti.json?id=id_impresa
  def create
    @prodotto = Prodotto.new(prodotto_params)
    @prodotto.impresa_id= params[:id]
    respond_to do |format|
      if @prodotto.save
        format.html { redirect_to impresa_prodotti_path(id: @prodotto.impresa_id ), notice: 'Prodotto was successfully created.' }
        format.json { render :show, status: :created, location: @prodotto }
      else
        format.html { render :new }
        format.json { render json: @prodotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imprese/:impresa_nome/prodotti?id=id_impresa
  # PATCH/PUT /imprese/:impresa_nome/prodotti.json?id=id_impresa
  def update
    respond_to do |format|
      if @prodotto.update(prodotto_params)
        format.html { redirect_to impresa_prodotti_path(id: @prodotto.impresa_id ), notice: 'Prodotto was successfully updated.' }
        format.json { render :show, status: :ok, location: @prodotto }
      else
        format.html { render :edit }
        format.json { render json: @prodotto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imprese/:impresa_nome/prodotti?id=id_impresa
  # DELETE /imprese/:impresa_nome/prodotti.json?id=id_impresa
  def destroy
    @prodotto.destroy
    respond_to do |format|
      format.html { redirect_to impresa_prodotti_path(id: @prodotto.impresa_id ), notice: 'Prodotto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #POST  /imprese/:impresa_nome/prodotti/:prodotto_nome/elimina_prodotto?id_p=id_prodotto
  def elimina_prodotto
    @prodotto= Prodotto.find(params[:id_p])
    @prodotto.clearQuantita
    @prodotto.setEliminato(true)
    redirect_back
  end

  private
    #Check su url cambiato manualmente
    def id_index_match
      impresa = Impresa.find(params[:id].to_i)
      if impresa.nome != params[:impresa_nome]
        redirect_to(impresa_prodotti_path(impresa_nome: impresa.nome, id: impresa.id))
      end
    end
    #Check su url cambiato manualmente
    def prodotto_impresa_match
      prodotto = Prodotto.find(params[:id_p])
      if prodotto.nome != params[:nome] || prodotto.impresa.nome != params[:impresa_nome]
        redirect_to( impresa_prodotto_path(impresa_nome: prodotto.impresa.nome, id_p: prodotto.id, nome: prodotto.nome))
      end
    end

    def impresa_abilitata #impresa deve essere verificata e NON congelata
      if !(@prodotto.impresa.verificato && !(@prodotto.impresa.congelato))
        redirect_back
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_prodotto
      @prodotto = Prodotto.find(params[:id_p])
    end

    def titolare_paypal?
      if params[:id] != nil
        impresa = Impresa.find(params[:id])
      else
        impresa= Prodotto.find(params[:id_p]).impresa
      end
      if !impresa.titolare.has_email_paypal
        redirect_to impresa_path(id: params[:id],nome: params[:impresa_nome])
      end
    end

    def prodotto_params
      params.require(:prodotto).permit(:nome, :prezzo, :qta, :descrizione,:impresa_id, :image, :eliminato)
    end
end

app/views/prodotti/_catalogo_vuoto.html.erb
  <div id="catalogo-vuoto">
    <div class="col-md-4">
      <%= image_tag "template/catalogo_vuoto.png",:class => "img-responsive",:size => '300x300'%>
    </div>
    <div class="col-md-8">
      <h2 id="catalogo-label"> Il catalogo di <%= params[:impresa_nome] %> è attualmente vuoto.</h2>
    </div>
  </div>

app/views/prodotti/_form.html.erb
<%- model_class = Prodotto -%>
<%= simple_form_for @prodotto, url: impresa_prodotti_path(nome: params[:impresa_nome],id: params[:id]), :html => { :class => 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
  check_boxes: :horizontal_radio_and_checkboxes,
  radio_buttons: :horizontal_radio_and_checkboxes,
  file: :horizontal_file_input,
  boolean: :horizontal_boolean
  }  do |f| %>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6" style="margin-top:30px;">
        <%= f.input :nome %>
        <%= error_span(@prodotto[:nome]) %>
        <%= f.input :prezzo %>
        <%= error_span(@prodotto[:prezzo]) %>
        <%= f.input :qta %>
      </div>
      <div class="col-md-6">
        <%= f.label :image %>
        <%= f.file_field :image %>
        <%= f.cropbox :image, height: 320, width: 240 %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= f.label :descrizione %>
        <%= f.text_area :descrizione, :class => "WYSIWYG" %>
        <%= error_span(@prodotto[:descrizione]) %>
      </div>
    </div>
  </div>
  <div class="panel-footer">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  impresa_prodotti_path(id: @prodotto.impresa_id), :class => 'btn btn-default',method: :get %>
  </div>
</div>
<% end %>

app/views/prodotti/_form_edit.html.erb
<%- model_class = Prodotto -%>
<%= simple_form_for @prodotto, url: impresa_prodotto_path, :html => { :class => 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
  check_boxes: :horizontal_radio_and_checkboxes,
  radio_buttons: :horizontal_radio_and_checkboxes,
  file: :horizontal_file_input,
  boolean: :horizontal_boolean
  } do |f| %>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6" style="margin-top:30px;">
          <%= f.input :nome, disabled: true %>
          <%= error_span(@prodotto[:nome]) %>
          <%= f.input :prezzo %>
          <%= error_span(@prodotto[:prezzo]) %>
          <%= f.input :qta %>
        </div>
        <div class="col-md-6">
          <%= f.label :image %>
          <%= f.file_field :image %>
          <%= f.cropbox :image, height: 200, width: 300 %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= f.label :descrizione %>
          <%= f.text_area :descrizione, :class => "WYSIWYG" %>
          <%= error_span(@prodotto[:descrizione]) %>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    impresa_prodotti_path(id: @prodotto.impresa_id), :class => 'btn btn-default',method: :get %>
    </div>
  </div>

  <%= hidden_field_tag(:id_p, @prodotto.id) %>
<% end %>

app/views/prodotti/_show.html.erb
<%- model_class = Prodotto -%>
<div class="container">
  <div class="page-header">
    <h1><%= prodotto.nome %></h1>
  </div>
  <div class="row">
    <div class="col-md-12"  >
      <div class="panel panel-default" style="height:30%">
        <div class="panel-body">
            <div class="col-md-6">
              <%= image_tag(prodotto.image, :class => "img-responsive") %>
            </div>
            <div class="col-md-6">
              <dl class="dl-horizontal text-right">
                <div class="row">
                  <dt><strong><%= model_class.human_attribute_name(:impresa_id) %>:</strong></dt>
                  <dd><%= Impresa.find(prodotto.impresa_id).getNome %></dd>
                </div>
                <div class="row">
                  <dt><strong><%= model_class.human_attribute_name(:prezzo) %>:</strong></dt>
                  <dd><%= prodotto.prezzo %></dd>
                </div>
                <div class="row">
                  <dt><strong><%= model_class.human_attribute_name(:quantità_Disponibile) %>:</strong></dt>
                  <dd><%= prodotto.qta %></dd>
                </div>
                <div class="row">
                  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
                  <dd><%= prodotto.nome %></dd>
                </div>
                <div class="row">
                  <dt><strong><%= model_class.human_attribute_name(:descrizione) %>:</strong></dt>
                  <dd><%= sanitize prodotto.descrizione %></dd>
                </div>
              </dl>
            </div>
          <div class="pull-right">
            <% if utente_signed_in? %>
              <% if !current_utente.isTitolare? %>
                <%= simple_form_for prodotto,url:  add_cart_carrello_path(current_utente.actable_id, prodotto_id: prodotto.id),method: :post , :html => { :class => 'form-horizontal' } do |f| %>
                  <%= f.button :submit , "Aggiungi al carrello" %>
                  <%= f.number_field :qta, :class => 'text_field',:value => 1 %>
                <%end%>
              <%end%>
              <% if current_utente.isMyImpresa?(Impresa.find(params[:id])) %>
                 <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_impresa_prodotto_path(nome: prodotto.nome,id_p: prodotto.id), :class => 'btn btn-default btn-xs',method: :get %>
                 <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      impresa_prodotto_elimina_prodotto_path(impresa_nome: prodotto.impresa.nome, prodotto_nome: prodotto.nome, id_p: prodotto.id),
                      :method => :post,:class => 'btn btn-xs btn-danger',
                      data: { :confirm => "\t\t\t\t\t\t\t\tATTENZIONE!!!! \nEliminando questo prodotto dovrai comunque evadere eventuali ordini in cui è presente. Continuare comunque?" }%>
              <% end %>
            <% else %>
              <%= button_to "Aggiungi al carrello",  new_utente_session_path, :class => "btn btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prodotti/edit.html.erb
<%- model_class = Prodotto -%>
<div class="container">
  <div class="page-header"></div>
  <div class="row">
    <div class="col-md-12">
      <%= render "form_edit" %>
    </div>
  </div>
</div>

app/views/prodotti/index.html.erb
<%- model_class = Prodotto -%>
<div class="container">
    <h1 class="text-center page-title">PRODOTTI</h1>
      <hr>
      <% if !Impresa.find(params[:id]).hasProdotti? %>
        <%= render "prodotti/catalogo_vuoto" %>
      <% else %>
        <% @prodotti.each do |prodotto| %>
          <% if !prodotto.eliminato %>
            <%= render :partial => "show", :locals => { :prodotto => prodotto }  %>
          <% end %>
        <% end %>
      <% end %>

      <%= hidden_field_tag(:id,params[:id]) %>
      <div id="azioni-catalogo">
        <hr>
      <%= link_to t('.profilo_impresa', :default => t("helpers.links.profilo_impresa")),
            impresa_path(nome: params[:impresa_nome],id: params[:id]),
            :class => 'btn btn-default',method: :get, :style=> 'float:left' %>
      <% if utente_signed_in? && current_utente.isMyImpresa?(Impresa.find(params[:id])) %>
        <%= link_to t('.new', :default => t("helpers.links.new")),
              new_impresa_prodotto_path(id: params[:id]),
              :class => 'btn btn-primary' ,method: :get , :style=> 'float:right'%>
      <% end %>
    </div>
</div>

app/views/prodotti/new.html.erb
<%- model_class = Prodotto -%>
<div class="container">
  <div class="page-header"></div>
  <div class="row">
    <%= render "form" %>
  </div>
</div>